<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.avaje</groupId>
    <artifactId>java11-oss</artifactId>
    <version>5.2</version>
  </parent>

  <groupId>io.avaje</groupId>
  <artifactId>avaje-provides-plugin-parent</artifactId>
  <packaging>pom</packaging>
  <version>2.3</version>
  <properties>
    <maven.compiler.release>24</maven.compiler.release>
  </properties>

  <modules>
    <module>avaje-provides-maven-plugin</module>
  </modules>
</project>
